services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: coffe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aysha@2026
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coffe
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Aysha@2026
    depends_on:
      - db

volumes:
  pgdata: